/**
 * Fixture-based tests that reproduce the "Verified numbers (2026-09-10)" from GOAL.md
 * against the snapshot in src/domain/__fixtures__/payments.json (generated by
 * `npm run snapshot`, read-only). If live data moves, regenerate the fixture and
 * document the drift in PROGRESS.md.
 */
import { describe, expect, it } from "vitest";
import raw from "../__fixtures__/payments.json";
import type { PaymentsSnapshot } from "../types";
import { buildRealm } from "../realm";
import { isSubdividedFarm } from "../lot";
import { round2, sum } from "../math";
import { groupIssuesByLot, summarizeQuality } from "../quality_human";

const fixture = raw as unknown as PaymentsSnapshot & { snapshotAt: string };
const ASOF = new Date("2026-09-11T00:00:00Z");
const realm = buildRealm(fixture, ASOF);

const money = (n: number) => round2(n);

describe("fixture: subdivided farms and lots", () => {
  it("has exactly 9 subdivided farms", () => {
    expect(realm.farms.map((f) => f.name).sort()).toEqual(
      ["Avery", "Eastland", "Franklin", "Franklin 2", "Freestone", "Lamar", "Promised Valley", "Titus", "Wichita"].sort(),
    );
  });

  it("matches the per-farm lot counts from GOAL.md (sums to 109)", () => {
    const counts = Object.fromEntries(realm.farms.map((f) => [f.name, f.lotRows]));
    expect(counts).toEqual({
      Eastland: 11,
      Wichita: 32,
      Lamar: 9,
      Avery: 14,
      Franklin: 6,
      "Franklin 2": 5,
      Freestone: 7,
      Titus: 6,
      "Promised Valley": 19,
    });
    expect(realm.lots).toHaveLength(109);
  });

  it("every farm's property rows equal its total_lots", () => {
    for (const f of realm.farms) expect(f.lotRows, f.name).toBe(f.totalLots);
  });

  it("excludes legacy one-off farms even when total_lots > 1 (Red River 1)", () => {
    const redRiver = fixture.farmAcquisitions.find((f) => f.farm_name === "Red River 1");
    expect(redRiver?.total_lots).toBe(2);
    expect(redRiver && isSubdividedFarm(redRiver)).toBe(false);
    expect(realm.lots.some((l) => l.farmName === "Red River 1")).toBe(false);
  });
});

describe("fixture: file cases on subdivided lots", () => {
  const lotIds = new Set(realm.lots.map((l) => l.propertyId));
  const onLots = fixture.fileCases.filter((c) => c.property_id && lotIds.has(c.property_id));

  it("counts 71 file cases with Σ sale_price = $8,986,794.30", () => {
    expect(onLots).toHaveLength(71);
    expect(money(sum(onLots.map((c) => c.sale_price)))).toBe(8_986_794.3);
  });

  it("splits 32 completed / 39 active and 7 cash / 64 financed", () => {
    expect(onLots.filter((c) => c.status === "completed")).toHaveLength(32);
    expect(onLots.filter((c) => c.status === "active")).toHaveLength(39);
    expect(onLots.filter((c) => c.deal_type === "cash")).toHaveLength(7);
    expect(onLots.filter((c) => c.deal_type === "financed")).toHaveLength(64);
  });

  it("ledger contract-price total reproduces $8,986,794.30 from the lots", () => {
    expect(money(sum(realm.lots.map((l) => l.fileCaseSalePrice)))).toBe(8_986_794.3);
    expect(realm.lots.filter((l) => l.fileCaseId)).toHaveLength(71);
  });

  it("rule-based sale price differs from contract price only by the documented mismatches", () => {
    const ruleTotal = money(sum(realm.lots.map((l) => l.salePrice)));
    const mismatched = realm.lots.filter((l) => l.noteOriginalAmount !== null && l.fileCaseSalePrice !== null && l.noteOriginalAmount !== l.fileCaseSalePrice);
    expect(mismatched.map((l) => l.name).sort()).toEqual(["Eastland — Lot 3", "Lamar — Lot 5", "Lamar — Lot 6", "Lamar — Lot 7", "Titus — Lot 6"]);
    const delta = money(sum(mismatched.map((l) => (l.fileCaseSalePrice ?? 0) - (l.noteOriginalAmount ?? 0))));
    expect(money(ruleTotal + delta)).toBe(8_986_794.3);
  });
});

describe("fixture: notes, note sales, distributions, costs", () => {
  it("has 15 note sales totalling $1,356,405.86", () => {
    expect(fixture.noteSales).toHaveLength(15);
    expect(money(sum(fixture.noteSales.map((s) => s.sale_price)))).toBe(1_356_405.86);
    expect(realm.treasury.totalAllNoteSales).toBe(1_356_405.86);
  });

  it("every sold note has a note_sales row and vice versa", () => {
    const sold = fixture.notes.filter((n) => n.is_sold);
    expect(sold).toHaveLength(15);
    const saleNoteIds = new Set(fixture.noteSales.map((s) => s.note_id));
    for (const n of sold) expect(saleNoteIds.has(n.id), n.note_code ?? "").toBe(true);
  });

  it("has 32 investor distributions totalling $793,990.46", () => {
    expect(fixture.investorDistributions).toHaveLength(32);
    expect(money(sum(fixture.investorDistributions.map((d) => d.amount)))).toBe(793_990.46);
    expect(realm.treasury.totalCashOut).toBe(793_990.46);
  });

  it("has 13 property_costs totalling $5,797,147.50", () => {
    expect(fixture.propertyCosts).toHaveLength(13);
    expect(money(sum(fixture.propertyCosts.map((c) => c.amount)))).toBe(5_797_147.5);
  });

  it("contains no test notes (filtered at the query boundary)", () => {
    expect(fixture.notes.every((n) => n.is_test === false)).toBe(true);
    expect(fixture.clients.every((c) => c.is_test === false)).toBe(true);
  });
});

describe("fixture: investors", () => {
  it("Townson Family is the only profit_share investor, on Wichita and Lamar", () => {
    const ps = realm.farms.filter((f) => f.dealType === "profit_share");
    expect(ps.map((f) => f.name).sort()).toEqual(["Lamar", "Wichita"]);
    expect(new Set(ps.map((f) => f.investorName))).toEqual(new Set(["Townson Family"]));
    const psInvestors = realm.investors.filter((i) => i.farms.some((f) => f.dealType === "profit_share"));
    expect(psInvestors.map((i) => i.name)).toEqual(["Townson Family"]);
  });

  it("Townson Family has received every distribution so far", () => {
    const townson = realm.investors.find((i) => i.name === "Townson Family");
    expect(townson?.totalPaidOut).toBe(793_990.46);
    expect(townson?.distributions).toHaveLength(32);
  });

  it("Lamar capital ($475,000) is fully returned; Wichita is not", () => {
    const lamar = realm.farms.find((f) => f.name === "Lamar");
    const wichita = realm.farms.find((f) => f.name === "Wichita");
    expect(lamar?.capitalReturned).toBe(475_000);
    expect(lamar?.capitalOutstanding).toBe(0);
    expect(wichita?.capitalOutstanding).toBe(round2(1_197_000 - (wichita?.capitalReturned ?? 0)));
    expect(wichita && wichita.capitalOutstanding > 0).toBe(true);
  });

  it("fixed-interest sponsors accrue at 20%/25% and have been paid nothing yet", () => {
    for (const f of realm.farms.filter((f) => f.dealType === "fixed_interest")) {
      expect([20, 25]).toContain(f.annualRatePct);
      expect(f.interest.paidToDate).toBe(0);
    }
    const eastland = realm.farms.find((f) => f.name === "Eastland");
    // 550,000 × 20% / 365 × 382 days (2025-08-25 → 2026-09-11)
    expect(eastland?.interest.daysAccruing).toBe(382);
    expect(eastland?.interest.accruedToDate).toBe(round2((550_000 * 0.2 * 382) / 365));
  });
});

describe("fixture: data quality", () => {
  const lotNames = (kind: string) => realm.quality.filter((q) => q.kind === kind).map((q) => q.lotName);

  it("lists Titus Lot 6, Lamar Lots 5/6/7 and Eastland Lot 3 as price mismatches", () => {
    expect(lotNames("price_mismatch").sort()).toEqual(["Eastland — Lot 3", "Lamar — Lot 5", "Lamar — Lot 6", "Lamar — Lot 7", "Titus — Lot 6"]);
  });

  it("flags Lamar Lot 5's reservation after its note start", () => {
    expect(lotNames("reservation_after_note_start")).toEqual(["Lamar — Lot 5"]);
  });

  it("flags farms with NULL investor_capital and the Red River 1 legacy oddity", () => {
    expect(realm.quality.filter((q) => q.kind === "farm_capital_null").map((q) => q.farmName).sort()).toEqual(["Ben White", "Sharps Rd"]);
    expect(realm.quality.some((q) => q.kind === "legacy_farm_with_lots" && q.farmName === "Red River 1")).toBe(true);
  });

  it("flags the real Eastland Lot 3 case whose buyer is a test client, without dropping it", () => {
    expect(lotNames("test_client_on_real_case")).toEqual(["Eastland — Lot 3"]);
    const lot = realm.lots.find((l) => l.name === "Eastland — Lot 3");
    expect(lot?.buyerIsTestClient).toBe(true);
    expect(lot?.stage).toBe("note_sold");
  });

  it("has no sold note without a sale", () => {
    expect(realm.quality.filter((q) => q.kind === "sold_note_without_sale")).toHaveLength(0);
  });

  it("groups the 33 issues into 18 lot cards and 3 farm cards, $21,801.50 of profit moved by price mismatches, oldest Ben White's blank capital", () => {
    const cards = groupIssuesByLot(realm.quality, "es");
    const summary = summarizeQuality(cards, ASOF.toISOString());
    expect(realm.quality).toHaveLength(33);
    expect(summary.issues).toBe(33);
    expect(summary.lotsWithIssues).toBe(18);
    expect(summary.farmsWithIssues).toBe(3);
    expect(cards.filter((c) => c.isFarm).map((c) => c.title).sort()).toEqual(["Ben White", "Red River 1", "Sharps Rd"]);
    expect(summary.priceMismatches).toBe(5);
    expect(summary.priceMismatchDollars).toBe(21_801.5);
    expect(summary.oldest?.card.title).toBe("Ben White");
    expect(summary.oldest?.issue.kind).toBe("farm_capital_null");
    expect(summary.oldest?.since).toBe("2024-07-30");
    expect(summary.oldest?.days).toBe(773);
    // Two different properties are both named "Red River 1" — two lot cards share a title on purpose.
    expect(cards.filter((c) => !c.isFarm && c.title === "Red River 1")).toHaveLength(2);
    // Every issue carries a business date except Eastland Lot 6's completed case without any date.
    const undated = realm.quality.filter((q) => q.since === null);
    expect(undated.map((q) => `${q.lotName}:${q.kind}`)).toEqual(["Eastland — Lot 6:completed_without_closing_date"]);
  });
});

describe("fixture: goal and rollups reconcile", () => {
  it("stage counts add up to 109 and sold lots equal closed + note_sold", () => {
    const g = realm.goal;
    expect(g.availableLots + g.reservedLots + g.closedLots).toBe(109);
    expect(realm.lots.filter((l) => l.stage === "note_sold")).toHaveLength(g.noteSoldLots);
    expect(g.noteSoldLots).toBe(14);
  });

  it("net profit to date equals the sum over farms and is positive but below the goal", () => {
    const farmsNet = round2(sum(realm.farms.map((f) => f.netProfit)));
    expect(realm.goal.netProfitToDate).toBe(farmsNet);
    expect(realm.goal.netProfitToDate).toBeGreaterThan(0);
    expect(realm.goal.remaining).toBe(round2(10_000_000 - realm.goal.netProfitToDate));
  });

  it("cash realized equals the treasury's farm-level cash in (including undated closings)", () => {
    expect(realm.goal.cashRealized).toBe(round2(realm.treasury.totalDownPayments + realm.treasury.totalNoteSales));
    // Eastland Lot 6: completed cash deal with no closing_date → surfaced as undated, not dropped
    expect(realm.treasury.undatedCashIn).toBe(90_000);
    expect(realm.treasury.totalCashIn).toBe(round2(realm.goal.cashRealized + realm.treasury.totalOtherNoteSales));
  });

  it("capital outstanding equals Σ investor_capital − Σ capital_return distributions on subdivided farms", () => {
    const capital = sum(realm.farms.map((f) => f.capitalDeployed));
    const returned = sum(fixture.investorDistributions.filter((d) => d.kind === "capital_return").map((d) => d.amount));
    expect(realm.goal.capitalOutstanding).toBe(round2(capital - returned));
  });

  it("produces a verdict sentence and a projection", () => {
    expect(realm.goal.verdict).toMatch(/lots\/month/);
    expect(realm.goal.lotsStillNeeded).toBeGreaterThan(0);
    expect(realm.goal.requiredLotsPerMonthToHitDeadline).toBeGreaterThan(0);
    expect(realm.goal.daysToDeadline).toBe(476);
  });

  it("chronicle contains the $1M and $2M milestones and no cumulative regression", () => {
    const milestones = realm.events.filter((e) => e.kind === "milestone").map((e) => e.milestone);
    expect(milestones).toEqual([1_000_000, 2_000_000]);
    let prev = 0;
    for (const e of realm.events) {
      expect(e.cumulativeNetProfit).toBeGreaterThanOrEqual(prev);
      prev = e.cumulativeNetProfit;
    }
  });

  it("computes at least 15 trophies with at least one earned and one unearned", () => {
    expect(realm.trophies.length).toBeGreaterThanOrEqual(15);
    expect(realm.trophies.some((t) => t.earned)).toBe(true);
    expect(realm.trophies.some((t) => !t.earned)).toBe(true);
  });

  it("oracle defaults come from real trailing averages", () => {
    const o = realm.oracleDefaults;
    expect(o.lotsPerMonth).toBe(realm.goal.closedLotsPerMonth);
    expect(o.avgSalePrice).toBeGreaterThan(50_000);
    expect(o.avgLandCost).toBeGreaterThan(10_000);
    expect(o.avgLotsPerFarm).toBe(realm.goal.avgLotsPerFarm);
  });
});
