/**
 * Fixture-based tests that reproduce the "Verified numbers (2026-09-10)" from GOAL.md
 * against the snapshot in src/domain/__fixtures__/payments.json (generated by
 * `npm run snapshot`, read-only). If live data moves, regenerate the fixture and
 * document the drift in PROGRESS.md.
 */
import { describe, expect, it } from "vitest";
import raw from "../__fixtures__/payments.json";
import type { PaymentsSnapshot } from "../types";
import { buildRealm } from "../realm";
import { isSubdividedFarm } from "../lot";
import { round2, sum } from "../math";
import { groupIssuesByLot, summarizeQuality } from "../quality_human";

const fixture = raw as unknown as PaymentsSnapshot & { snapshotAt: string };
const ASOF = new Date("2026-09-11T00:00:00Z");
const realm = buildRealm(fixture, ASOF);

const money = (n: number) => round2(n);

describe("fixture: subdivided farms and lots", () => {
  it("has exactly 10 subdivided farms (Lakeview was added to Payments on 2026-09-11 at 21:15Z)", () => {
    expect(realm.farms.map((f) => f.name).sort()).toEqual(
      ["Avery", "Eastland", "Franklin", "Franklin 2", "Freestone", "Lakeview", "Lamar", "Promised Valley", "Titus", "Wichita"].sort(),
    );
  });

  it("matches the per-farm lot counts from GOAL.md plus Lakeview's 12 (sums to 121)", () => {
    const counts = Object.fromEntries(realm.farms.map((f) => [f.name, f.lotRows]));
    expect(counts).toEqual({
      Eastland: 11,
      Wichita: 32,
      Lamar: 9,
      Avery: 14,
      Franklin: 6,
      "Franklin 2": 5,
      Freestone: 7,
      Titus: 6,
      "Promised Valley": 19,
      Lakeview: 12,
    });
    expect(realm.lots).toHaveLength(121);
  });

  it("every farm's property rows equal its total_lots", () => {
    for (const f of realm.farms) expect(f.lotRows, f.name).toBe(f.totalLots);
  });

  it("excludes legacy one-off farms even when total_lots > 1 (Red River 1)", () => {
    const redRiver = fixture.farmAcquisitions.find((f) => f.farm_name === "Red River 1");
    expect(redRiver?.total_lots).toBe(2);
    expect(redRiver && isSubdividedFarm(redRiver)).toBe(false);
    expect(realm.lots.some((l) => l.farmName === "Red River 1")).toBe(false);
  });
});

describe("fixture: file cases on subdivided lots", () => {
  const lotIds = new Set(realm.lots.map((l) => l.propertyId));
  const onLots = fixture.fileCases.filter((c) => c.property_id && lotIds.has(c.property_id));

  it("counts 71 file cases with Σ sale_price = $8,984,992.30 (Titus Lot 6 re-priced from $141,802 to $140,000 on 2026-09-11)", () => {
    expect(onLots).toHaveLength(71);
    expect(money(sum(onLots.map((c) => c.sale_price)))).toBe(8_984_992.3);
  });

  it("splits 37 completed / 34 active and 7 cash / 64 financed (Lamar 5, 6, 7 and Eastland 4, 8 completed on 2026-09-11)", () => {
    expect(onLots.filter((c) => c.status === "completed")).toHaveLength(37);
    expect(onLots.filter((c) => c.status === "active")).toHaveLength(34);
    expect(onLots.filter((c) => c.deal_type === "cash")).toHaveLength(7);
    expect(onLots.filter((c) => c.deal_type === "financed")).toHaveLength(64);
  });

  it("ledger contract-price total reproduces $8,984,992.30 from the lots", () => {
    expect(money(sum(realm.lots.map((l) => l.fileCaseSalePrice)))).toBe(8_984_992.3);
    expect(realm.lots.filter((l) => l.fileCaseId)).toHaveLength(71);
  });

  it("rule-based sale price differs from contract price only by the four documented mismatches (Titus Lot 6 now agrees with its note)", () => {
    const ruleTotal = money(sum(realm.lots.map((l) => l.salePrice)));
    const mismatched = realm.lots.filter((l) => l.noteOriginalAmount !== null && l.fileCaseSalePrice !== null && l.noteOriginalAmount !== l.fileCaseSalePrice);
    expect(mismatched.map((l) => l.name).sort()).toEqual(["Eastland — Lot 3", "Lamar — Lot 5", "Lamar — Lot 6", "Lamar — Lot 7"]);
    const delta = money(sum(mismatched.map((l) => (l.fileCaseSalePrice ?? 0) - (l.noteOriginalAmount ?? 0))));
    expect(money(ruleTotal + delta)).toBe(8_984_992.3);
  });
});

describe("fixture: notes, note sales, distributions, costs", () => {
  it("has 15 note sales totalling $1,356,405.86", () => {
    expect(fixture.noteSales).toHaveLength(15);
    expect(money(sum(fixture.noteSales.map((s) => s.sale_price)))).toBe(1_356_405.86);
    expect(realm.treasury.totalAllNoteSales).toBe(1_356_405.86);
  });

  it("every sold note has a note_sales row and vice versa", () => {
    const sold = fixture.notes.filter((n) => n.is_sold);
    expect(sold).toHaveLength(15);
    const saleNoteIds = new Set(fixture.noteSales.map((s) => s.note_id));
    for (const n of sold) expect(saleNoteIds.has(n.id), n.note_code ?? "").toBe(true);
  });

  it("has 32 investor distributions totalling $793,990.46", () => {
    expect(fixture.investorDistributions).toHaveLength(32);
    expect(money(sum(fixture.investorDistributions.map((d) => d.amount)))).toBe(793_990.46);
    expect(realm.treasury.totalCashOut).toBe(793_990.46);
  });

  it("has 24 property_costs totalling $5,901,906: 13 purchases ($5,797,147.50) and 11 surveys ($104,758.50)", () => {
    expect(fixture.propertyCosts).toHaveLength(24);
    expect(money(sum(fixture.propertyCosts.map((c) => c.amount)))).toBe(5_901_906);
    const purchases = fixture.propertyCosts.filter((c) => c.category === "purchase");
    const surveys = fixture.propertyCosts.filter((c) => c.category === "survey");
    expect(purchases).toHaveLength(13);
    expect(money(sum(purchases.map((c) => c.amount)))).toBe(5_797_147.5);
    expect(surveys).toHaveLength(11);
    expect(money(sum(surveys.map((c) => c.amount)))).toBe(104_758.5);
    expect(purchases.length + surveys.length).toBe(fixture.propertyCosts.length);
  });

  it("contains no test notes (filtered at the query boundary)", () => {
    expect(fixture.notes.every((n) => n.is_test === false)).toBe(true);
    expect(fixture.clients.every((c) => c.is_test === false)).toBe(true);
  });
});

describe("fixture: investors", () => {
  it("Townson Family is the only profit_share investor, on Wichita, Lamar and the new Lakeview", () => {
    const ps = realm.farms.filter((f) => f.dealType === "profit_share");
    expect(ps.map((f) => f.name).sort()).toEqual(["Lakeview", "Lamar", "Wichita"]);
    expect(new Set(ps.map((f) => f.investorName))).toEqual(new Set(["Townson Family"]));
    const psInvestors = realm.investors.filter((i) => i.farms.some((f) => f.dealType === "profit_share"));
    expect(psInvestors.map((i) => i.name)).toEqual(["Townson Family"]);
  });

  it("Townson Family has received every distribution so far", () => {
    const townson = realm.investors.find((i) => i.name === "Townson Family");
    expect(townson?.totalPaidOut).toBe(793_990.46);
    expect(townson?.distributions).toHaveLength(32);
  });

  it("Lamar's capital is $484,000 (purchase + survey) and $475,000 has been returned: $9,000 still outstanding, so it is no longer fully returned; Wichita is not either", () => {
    const lamar = realm.farms.find((f) => f.name === "Lamar");
    const wichita = realm.farms.find((f) => f.name === "Wichita");
    // 2026-09-11: Payments set investor_capital to purchase + survey ($475,000 + $9,000). The $475,000 returned no longer covers it — a data fact, not a bug.
    expect(lamar?.capitalDeployed).toBe(484_000);
    expect(lamar?.capitalReturned).toBe(475_000);
    expect(lamar?.capitalOutstanding).toBe(9_000);
    expect(wichita?.capitalDeployed).toBe(1_217_000);
    expect(wichita?.capitalOutstanding).toBe(round2(1_217_000 - (wichita?.capitalReturned ?? 0)));
    expect(wichita && wichita.capitalOutstanding > 0).toBe(true);
  });

  it("fixed-interest sponsors accrue at 20%/25% and have been paid nothing yet", () => {
    for (const f of realm.farms.filter((f) => f.dealType === "fixed_interest")) {
      expect([20, 25]).toContain(f.annualRatePct);
      expect(f.interest.paidToDate).toBe(0);
    }
    const eastland = realm.farms.find((f) => f.name === "Eastland");
    // 565,000 (purchase $550,000 + survey $15,000) × 20% / 365 × 382 days (2025-08-25 → 2026-09-11)
    expect(eastland?.capitalDeployed).toBe(565_000);
    expect(eastland?.interest.daysAccruing).toBe(382);
    expect(eastland?.interest.accruedToDate).toBe(round2((565_000 * 0.2 * 382) / 365));
    expect(eastland?.interest.accruedToDate).toBe(118_263.01);
  });
});

describe("fixture: data quality", () => {
  const lotNames = (kind: string) => realm.quality.filter((q) => q.kind === kind).map((q) => q.lotName);

  it("lists Lamar Lots 5/6/7 and Eastland Lot 3 as price mismatches (Titus Lot 6 was corrected to $140,000 on 2026-09-11)", () => {
    expect(lotNames("price_mismatch").sort()).toEqual(["Eastland — Lot 3", "Lamar — Lot 5", "Lamar — Lot 6", "Lamar — Lot 7"]);
    const titus6 = realm.lots.find((l) => l.name === "Titus — Lot 6");
    expect(titus6?.fileCaseSalePrice).toBe(140_000);
    expect(titus6?.noteOriginalAmount).toBe(140_000);
  });

  it("no reservation follows its note start any more: Lamar Lot 5's reservation_date was corrected to 2025-09-07 on 2026-09-11", () => {
    expect(lotNames("reservation_after_note_start")).toEqual([]);
    const lamar5 = realm.lots.find((l) => l.name === "Lamar — Lot 5");
    expect(lamar5?.reservationDate).toBe("2025-09-07");
    expect(lamar5?.closeDate).toBe("2025-11-05");
  });

  it("flags farms with NULL investor_capital and the Red River 1 legacy oddity", () => {
    expect(realm.quality.filter((q) => q.kind === "farm_capital_null").map((q) => q.farmName).sort()).toEqual(["Ben White", "Sharps Rd"]);
    expect(realm.quality.some((q) => q.kind === "legacy_farm_with_lots" && q.farmName === "Red River 1")).toBe(true);
  });

  it("flags the real Eastland Lot 3 case whose buyer is a test client, without dropping it", () => {
    expect(lotNames("test_client_on_real_case")).toEqual(["Eastland — Lot 3"]);
    const lot = realm.lots.find((l) => l.name === "Eastland — Lot 3");
    expect(lot?.buyerIsTestClient).toBe(true);
    expect(lot?.stage).toBe("note_sold");
  });

  it("has no sold note without a sale", () => {
    expect(realm.quality.filter((q) => q.kind === "sold_note_without_sale")).toHaveLength(0);
  });

  it("groups the 24 issues into 14 lot cards and 3 farm cards, $19,999.50 of profit moved by price mismatches, oldest Ben White's blank capital", () => {
    const cards = groupIssuesByLot(realm.quality, "es");
    const summary = summarizeQuality(cards, ASOF.toISOString());
    // 33 before 2026-09-11: the six file cases that moved to completed with closing dates cleared five active_file_case_with_note
    // (Lamar 5, 6, 7; Eastland 4, 8) and Eastland Lot 6's completed_without_closing_date; Lamar Lot 5's corrected reservation cleared reservation_after_note_start.
    // 26 → 24 at 21:17Z the same day: Titus Lot 6's file case now matches its note ($140,000 / $5,000 down), clearing its price and down-payment mismatches.
    expect(realm.quality).toHaveLength(24);
    expect(summary.issues).toBe(24);
    expect(summary.lotsWithIssues).toBe(14);
    expect(summary.farmsWithIssues).toBe(3);
    expect(lotNames("active_file_case_with_note")).toEqual(["Promised Valley — Lot 3"]);
    expect(lotNames("completed_without_closing_date")).toEqual(["Eastland — Lot 2"]);
    expect(cards.filter((c) => c.isFarm).map((c) => c.title).sort()).toEqual(["Ben White", "Red River 1", "Sharps Rd"]);
    expect(summary.priceMismatches).toBe(4);
    expect(summary.priceMismatchDollars).toBe(19_999.5);
    expect(summary.oldest?.card.title).toBe("Ben White");
    expect(summary.oldest?.issue.kind).toBe("farm_capital_null");
    expect(summary.oldest?.since).toBe("2024-07-30");
    expect(summary.oldest?.days).toBe(773);
    // Two different properties are both named "Red River 1" — two lot cards share a title on purpose.
    expect(cards.filter((c) => !c.isFarm && c.title === "Red River 1")).toHaveLength(2);
    // Every issue carries a business date now that Eastland Lot 6 has its closing date (2026-07-09).
    const undated = realm.quality.filter((q) => q.since === null);
    expect(undated.map((q) => `${q.lotName}:${q.kind}`)).toEqual([]);
  });
});

describe("fixture: goal and rollups reconcile", () => {
  it("stage counts add up to 121 (Lakeview's 12 lots are all available) and sold lots equal closed + note_sold", () => {
    const g = realm.goal;
    expect(g.availableLots + g.reservedLots + g.closedLots).toBe(121);
    expect(realm.farms.find((f) => f.name === "Lakeview")?.stages).toEqual({ available: 12, reserved: 0, closed: 0, note_sold: 0 });
    expect(realm.lots.filter((l) => l.stage === "note_sold")).toHaveLength(g.noteSoldLots);
    expect(g.noteSoldLots).toBe(14);
  });

  it("net profit to date equals the sum over farms and is positive but below the goal", () => {
    const farmsNet = round2(sum(realm.farms.map((f) => f.netProfit)));
    expect(realm.goal.netProfitToDate).toBe(farmsNet);
    expect(realm.goal.netProfitToDate).toBeGreaterThan(0);
    expect(realm.goal.remaining).toBe(round2(10_000_000 - realm.goal.netProfitToDate));
  });

  it("cash realized equals the treasury's farm-level cash in; no closing is undated any more", () => {
    expect(realm.goal.cashRealized).toBe(round2(realm.treasury.totalDownPayments + realm.treasury.totalNoteSales));
    // Eastland Lot 6's $90,000 cash deal carried no closing_date until 2026-09-11 (closed 2026-07-09); nothing is undated now
    expect(realm.treasury.undatedCashIn).toBe(0);
    expect(realm.lots.find((l) => l.name === "Eastland — Lot 6")?.closeDate).toBe("2026-07-09");
    expect(realm.treasury.totalCashIn).toBe(round2(realm.goal.cashRealized + realm.treasury.totalOtherNoteSales));
  });

  it("capital outstanding equals Σ investor_capital − Σ capital_return distributions on subdivided farms", () => {
    const capital = sum(realm.farms.map((f) => f.capitalDeployed));
    const returned = sum(fixture.investorDistributions.filter((d) => d.kind === "capital_return").map((d) => d.amount));
    expect(realm.goal.capitalOutstanding).toBe(round2(capital - returned));
  });

  it("produces a verdict sentence and a projection", () => {
    expect(realm.goal.verdict).toMatch(/lots\/month/);
    expect(realm.goal.lotsStillNeeded).toBeGreaterThan(0);
    expect(realm.goal.requiredLotsPerMonthToHitDeadline).toBeGreaterThan(0);
    expect(realm.goal.daysToDeadline).toBe(476);
  });

  it("chronicle contains the $1M and $2M milestones and no cumulative regression", () => {
    const milestones = realm.events.filter((e) => e.kind === "milestone").map((e) => e.milestone);
    expect(milestones).toEqual([1_000_000, 2_000_000]);
    let prev = 0;
    for (const e of realm.events) {
      expect(e.cumulativeNetProfit).toBeGreaterThanOrEqual(prev);
      prev = e.cumulativeNetProfit;
    }
  });

  it("computes at least 15 trophies with at least one earned and one unearned", () => {
    expect(realm.trophies.length).toBeGreaterThanOrEqual(15);
    expect(realm.trophies.some((t) => t.earned)).toBe(true);
    expect(realm.trophies.some((t) => !t.earned)).toBe(true);
  });

  it("oracle defaults come from real trailing averages", () => {
    const o = realm.oracleDefaults;
    expect(o.lotsPerMonth).toBe(realm.goal.closedLotsPerMonth);
    expect(o.avgSalePrice).toBeGreaterThan(50_000);
    expect(o.avgLandCost).toBeGreaterThan(10_000);
    expect(o.avgLotsPerFarm).toBe(realm.goal.avgLotsPerFarm);
  });
});
