import {
  ArrowRightFromLine,
  Award,
  BookOpen,
  BookMarked,
  Castle,
  Coins,
  Compass,
  Crosshair,
  Crown,
  Eye,
  Feather,
  Flame,
  Footprints,
  Gem,
  Hexagon,
  Hourglass,
  Landmark,
  Map,
  Medal,
  Radar,
  Sailboat,
  Scroll,
  ScrollText,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Swords,
  Target,
  Timer,
  Trophy,
  Users,
  Vault,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { ThemeId } from "./themes";

export type IconName = "brand" | "throne" | "council" | "warplan" | "exodus" | "realm" | "quests" | "pipeline" | "sponsors" | "treasury" | "oracle" | "chronicle" | "trophies" | "quality";

/**
 * Iconography per theme. Iron Crown speaks in war and stone, Gilded Realm in scribes and heraldry,
 * Neon Kingdom in HUD sensors. Same glyph library, three dialects.
 */
const ICONS: Record<ThemeId, Record<IconName, LucideIcon>> = {
  "iron-crown": {
    brand: Castle,
    throne: Crown,
    council: Scroll,
    warplan: Target,
    exodus: Footprints,
    realm: Map,
    quests: Swords,
    pipeline: Hourglass,
    sponsors: Shield,
    treasury: Coins,
    oracle: Eye,
    chronicle: BookOpen,
    trophies: Medal,
    quality: ShieldAlert,
  },
  "gilded-realm": {
    brand: Landmark,
    throne: Crown,
    council: ScrollText,
    warplan: Compass,
    exodus: Sailboat,
    realm: Map,
    quests: ScrollText,
    pipeline: Hourglass,
    sponsors: Users,
    treasury: Gem,
    oracle: Sparkles,
    chronicle: Feather,
    trophies: Award,
    quality: ShieldCheck,
  },
  "neon-kingdom": {
    brand: Hexagon,
    throne: Zap,
    council: Sparkles,
    warplan: Crosshair,
    exodus: ArrowRightFromLine,
    realm: Radar,
    quests: Scroll,
    pipeline: Timer,
    sponsors: Users,
    treasury: Vault,
    oracle: Eye,
    chronicle: BookMarked,
    trophies: Trophy,
    quality: Flame,
  },
};

export function themeIcon(theme: ThemeId, name: IconName): LucideIcon {
  return ICONS[theme][name];
}
